### ISSUE TITLE
flatpack, change tomcat port?

### ISSUE THREAD

**Issue by RhanCandia** [Suwayomi/Suwayomi-VaadinUI#149]
It looks like the flatpack version is using port 8080 to initialize the tomcat server.

I can't use port 8080 in my machine because it is already used by another service.

Is there a config where I can override the tomcat port? An environment variable?

The app wouldn't launch because my port 8080 is already taken.

**Comment by aless2003** [comment]
Ah I'm actually changing the port in an upcoming version to 3901 (seems like nothing uses that). I'm pretty giving -Dserver.port=<port number> would change the port as well, albeit the notifications take you there correctly then.
I probably should have made it configurable, but when I made this, it was a project for me only really, so I never bothered😅

**Comment by RhanCandia** [comment]
> Ah I'm actually changing the port in an upcoming version to 3901 (seems like nothing uses that). I'm pretty giving sure -Dserver.port=<port number> would change the port as well, albeit the notifications won't take you there correctly then. I probably should have made it configurable, but when I made this, it was a project for me only really, so I never bothered😅

Thanks for the response.
I went back here to say that I was able to override the port by adding --server.port=<port>. I managed to run it now. I was suprised to see you already responded with the same answer.

Thanks for the quick response. And thanks for you contribution to the community! I'll close this issue now.

**Comment by aless2003** [comment]
Roger that, have a nice day :)
