### ISSUE TITLE
running jar in mac os monterey doesn't open

### ISSUE THREAD

**Issue by imed-ghomari** [Suwayomi/Suwayomi-VaadinUI#152]
i use the jar because the latest mac app is not supported in my mac os version.

![image](https://github.com/user-attachments/assets/9a363f6d-11bd-48a7-9b76-64f484608947)

**Comment by aless2003** [comment]
Yeah, I won't lie, the Mac version is utterly untested, I don't own a mac, nor do I have access to one.
Try checking in "~/Library/Application Support" if there is a .TachideskVaadinUI file. If so check if there are logs in there and send them over. If not, I don't think I can do much unfortunately

**Comment by imeed166** [comment]
There is the tachidesk folder (because I used to use the original tachidesk) but no "tachideskvaadinUi" file within or outside of it. Thanks for responding.

**Comment by aless2003** [comment]
Hmm I see, very sorry then, if I ever get access to a mac, I'll re-open this. The jar should still work fine though.
Have a good one and thanks for using my little app
