### ISSUE TITLE
it does not work after extension removal

### ISSUE THREAD

**Issue by dnet890** [Suwayomi/Suwayomi-VaadinUI#91]
Hi
I understand that extension has been removed from central repo. But, I try to download latest version and it does not worked on Ubuntu
![2024-01-09_14-19](https://github.com/Suwayomi/Tachidesk-VaadinUI/assets/29157187/6b449363-00e9-46f9-86ad-39244864ce61)

**Comment by aless2003** [comment]
Sorry, what exactly doesn't work? 
Like, does the server not start or does the settings page not work correctly?

**Comment by dtantono** [comment]
it just does not start looking for new manga

**Comment by aless2003** [comment]
Like the library doesn't update?

**Comment by aless2003** [comment]
Or is it an issue with an extension, because those I have no control over

**Comment by dtantono** [comment]
it does not load all of the extensions that I set up from suwayomi launcher. What do you think?
![2024-01-09_15-24_1](https://github.com/Suwayomi/Tachidesk-VaadinUI/assets/29157187/c52c09db-7585-401c-a4d8-e6f153c9853d)
![2024-01-09_15-24](https://github.com/Suwayomi/Tachidesk-VaadinUI/assets/29157187/b95d9e70-f7a8-47d9-ba38-64ba3e3c09d7)

**Comment by dtantono** [comment]
Sorry, how to add additional repo for VaadinUI?

**Comment by aless2003** [comment]
I don't really have such a feature. Is that a thing on the other suwayomi UIs? If so I might look into it.
You can also try just using a dedicated server and just telling VaadinUI through the settings to use that server instead.

**Comment by dtantono** [comment]
well, with the tachiyomi shutting down it's central repo. it is necessary to add external repo to get the manga we needed and it looks like I have to rely on suwayomi main launcher that support external sources to get it work. Is that so?

**Comment by aless2003** [comment]
Oh hold up, they do? Damn, didn't know that. I'll take a look into how I might be able to add external repos. For now you might wanna try to use the main launcher. You should still be able to use that server (the one the main launcher starts) with VaadinUI by setting the server url to http://localhost:4567
Really sorry for the inconveniences!

**Comment by dtantono** [comment]
this is the official news https://tachiyomi.org/news/2024-01-09-extensions-removal

**Comment by aless2003** [comment]
Ah dann, I'll see what I can do when I get home

**Comment by dtantono** [comment]
I suggest you start targeting those two repositories. Those two are actively maintained atm. https://github.com/keiyoushi/extensions and https://github.com/ThePBone/tachiyomi-extensions-revived

**Comment by aless2003** [comment]
Will do, but I likey gotta merch the graphql branch into master to get this working so it'll likely not be a fast transition, but I'll give my best. Thanks for the heads-up

**Comment by mangade73** [comment]
Updated and fortunately i already installed extensions, just pick "trust". But when i try to see anothers is empty.. In broswe, extensions... Except already installed. 

Try to install officials but its nothing, duplicate in list. So i removed it again. 

Try to find a way to add extensions again or another apps... 

Thank you.

**Comment by aless2003** [comment]
Little update, I found a way to add custom ones, for now I'll patch everything up in the next couple days for necessity and just use a default repo. Customizing the repos will be added later on

**Comment by Syer10** [comment]
Fyi you cannot add a default repo(unless its the Tachi self-hosted extensions repo) due to copywrite issues.

**Comment by aless2003** [comment]
> Fyi you cannot add a default repo(unless its the Tachyomi self-hosted extensions repo) due to copyright issues.

I see, well uh that throws some stones in the path. Need to make the whole UI now after all. Yikes 😬
Would I be able to point Users to a repo they "might wanna add", so to speak?

**Comment by Syer10** [comment]
We shouldn't be endorsing repos either 😞

**Comment by aless2003** [comment]
Uff, that will be one hell of a confusing user experience :/

**Comment by aless2003** [comment]
Man, I shouldn't write stuff when I'm tired and pissed at the same time. But I think this can pass and not be counted as copyright infringing in any freaking way or so help me God >.>
![image](https://github.com/Suwayomi/Tachidesk-VaadinUI/assets/46018087/619d2911-8b2e-4786-8c62-c0c0d771403c)

**Comment by aless2003** [comment]
Status Update:
I've managed to get the external extension repo going. In the next couple days, I'll finish styling it (to the best of my very bad abilities) and try to get everything to an acceptable state. I'll also have some bugs to fix coming from the GraphQL migration. Meaning this should (hopefully) come out soon, no promises though.

**Comment by aless2003** [comment]
@dtantono The new Release should fix this issue. Will keep it open until it's merged into master.
https://github.com/Suwayomi/Tachidesk-VaadinUI/releases/tag/v1.1.0-pre

**Comment by aless2003** [comment]
@dtantono 
This is now in a stable release, so I'll close this issue.

Here's the release: https://github.com/Suwayomi/Tachidesk-VaadinUI/releases/tag/v1.2.0

Thanks for your issue and have a good day!
